In [2]:
!pip install datasets sentence-transformers chromadb openai pandas numpy python-dotenv tqdm -q

WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\MAITHILI\\AppData\\Roaming\\Python\\Python39\\site-packages\\google\\~rotobuf\\internal\\_api_implementation.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)

In [4]:
!pip install chromadb

Collecting chromadb
  Using cached chromadb-1.5.7-cp39-abi3-win_amd64.whl (23.1 MB)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (4.15.0)
Collecting opentelemetry-api>=1.2.0
  Using cached opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
Collecting overrides>=7.3.1
  Using cached overrides-7.7.0-py3-none-any.whl (17 kB)
Requirement already satisfied: numpy>=1.22.5 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (1.26.4)
Requirement already satisfied: importlib-resources in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (6.4.4)
Collecting kubernetes>=28.1.0
  Using cached kubernetes-35.0.0-py2.py3-none-any.whl (2.0 MB)
Collecting grpcio>=1.58.0
  Using cached grpcio-1.80.0-cp39-cp39-win_amd64.whl (4.9 MB)
Requirement already satisfied: orjson>=3.9.12 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (3.10.3)
Collecting onnxruntime>=1.14.1
  Using cached onnxruntime-1.19.2-cp39-cp39-win_amd64.whl (11.1 MB)
Requirement already satisfied: pydantic>=2.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (2.10.4)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0
  Using cached opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl (20 kB)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (6.0.2)
Requirement already satisfied: httpx>=0.27.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (13.9.4)
Collecting opentelemetry-sdk>=1.2.0
  Using cached opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
Requirement already satisfied: typer>=0.9.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (0.15.2)
Collecting mmh3>=4.0.1
  Using cached mmh3-5.2.0-cp39-cp39-win_amd64.whl (41 kB)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (9.1.2)
Collecting pypika>=0.48.9
  Using cached pypika-0.51.1-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (0.21.0)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (1.4.3)
Collecting jsonschema>=4.19.0
  Using cached jsonschema-4.25.1-py3-none-any.whl (90 kB)
Collecting uvicorn[standard]>=0.18.3
  Using cached uvicorn-0.39.0-py3-none-any.whl (68 kB)
Collecting build>=1.0.3
  Using cached build-1.4.2-py3-none-any.whl (24 kB)
Collecting bcrypt>=4.0.1
  Using cached bcrypt-5.0.0-cp39-abi3-win_amd64.whl (150 kB)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\maithili\anaconda3\lib\site-packages (from chromadb) (4.66.4)
Collecting pydantic-settings>=2.0
  Using cached pydantic_settings-2.11.0-py3-none-any.whl (48 kB)
Requirement already satisfied: colorama in c:\users\maithili\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: importlib-metadata>=4.6 in c:\users\maithili\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (8.7.0)
Collecting packaging>=24.0
  Using cached packaging-26.0-py3-none-any.whl (74 kB)
Requirement already satisfied: tomli>=1.1.0 in c:\users\maithili\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (2.0.1)
Requirement already satisfied: pyproject_hooks in c:\users\maithili\anaconda3\lib\site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: idna in c:\users\maithili\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: anyio in c:\users\maithili\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (3.5.0)
Requirement already satisfied: certifi in c:\users\maithili\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\maithili\anaconda3\lib\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\maithili\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\maithili\anaconda3\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.18.1)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Collecting attrs>=22.2.0
  Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Collecting referencing>=0.28.4
  Using cached referencing-0.36.2-py3-none-any.whl (26 kB)
Requirement already satisfied: durationpy>=0.7 in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: requests-oauthlib in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.58.0)
Requirement already satisfied: requests in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.32.3)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.26.20)
Requirement already satisfied: six>=1.9.0 in c:\users\maithili\anaconda3\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: flatbuffers in c:\users\maithili\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (23.3.3)
Requirement already satisfied: sympy in c:\users\maithili\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (1.10.1)
Requirement already satisfied: protobuf in c:\users\maithili\anaconda3\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting opentelemetry-proto==1.40.0
  Using cached opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
Collecting opentelemetry-exporter-otlp-proto-common==1.40.0
  Using cached opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl (18 kB)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\maithili\anaconda3\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.70.0)
Collecting opentelemetry-semantic-conventions==0.61b0
  Using cached opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic>=2.0->chromadb) (2.27.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic>=2.0->chromadb) (0.7.0)
Collecting typing-inspection>=0.4.0
  Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic-settings>=2.0->chromadb) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\maithili\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\maithili\anaconda3\lib\site-packages (from rich>=10.11.0->chromadb) (2.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in c:\users\maithili\anaconda3\lib\site-packages (from tokenizers>=0.13.2->chromadb) (0.24.5)
Requirement already satisfied: click>=8.0.0 in c:\users\maithili\anaconda3\lib\site-packages (from typer>=0.9.0->chromadb) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\maithili\anaconda3\lib\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: websockets>=10.4 in c:\users\maithili\anaconda3\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Collecting httptools>=0.6.3
  Using cached httptools-0.7.1-cp39-cp39-win_amd64.whl (86 kB)
Collecting watchfiles>=0.13
  Using cached watchfiles-1.1.1-cp39-cp39-win_amd64.whl (289 kB)
Requirement already satisfied: zipp>=3.1.0 in c:\users\maithili\anaconda3\lib\site-packages (from importlib-resources->chromadb) (3.23.0)
Requirement already satisfied: filelock in c:\users\maithili\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.6.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\maithili\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2024.5.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\maithili\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\maithili\anaconda3\lib\site-packages (from anyio->httpx>=0.27.0->chromadb) (1.2.0)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\maithili\anaconda3\lib\site-packages (from requests->kubernetes>=28.1.0->chromadb) (2.0.4)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\maithili\anaconda3\lib\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: mpmath>=0.19 in c:\users\maithili\anaconda3\lib\site-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.2.1)
Requirement already satisfied: pyreadline3 in c:\users\maithili\anaconda3\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime>=1.14.1->chromadb) (3.4.1)
Installing collected packages: typing-inspection, pypika, packaging, overrides, opentelemetry-proto, mmh3, humanfriendly, httptools, grpcio, bcrypt, attrs, watchfiles, uvicorn, referencing, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, coloredlogs, build, pydantic-settings, opentelemetry-semantic-conventions, onnxruntime, kubernetes, jsonschema-specifications, opentelemetry-sdk, jsonschema, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.53.0
    Uninstalling grpcio-1.53.0:
      Successfully uninstalled grpcio-1.53.0
  Attempting uninstall: bcrypt
    Found existing installation: bcrypt 3.2.0
    Uninstalling bcrypt-3.2.0:
      Successfully uninstalled bcrypt-3.2.0
  Attempting uninstall: attrs
    Found existing installation: attrs 21.4.0
    Uninstalling attrs-21.4.0:
      Successfully uninstalled attrs-21.4.0
  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 4.16.0
    Uninstalling jsonschema-4.16.0:
      Successfully uninstalled jsonschema-4.16.0
Successfully installed attrs-26.1.0 bcrypt-5.0.0 build-1.4.2 chromadb-1.5.7 coloredlogs-15.0.1 grpcio-1.80.0 httptools-0.7.1 humanfriendly-10.0 jsonschema-4.25.1 jsonschema-specifications-2025.9.1 kubernetes-35.0.0 mmh3-5.2.0 onnxruntime-1.19.2 opentelemetry-api-1.40.0 opentelemetry-exporter-otlp-proto-common-1.40.0 opentelemetry-exporter-otlp-proto-grpc-1.40.0 opentelemetry-proto-1.40.0 opentelemetry-sdk-1.40.0 opentelemetry-semantic-conventions-0.61b0 overrides-7.7.0 packaging-26.0 pydantic-settings-2.11.0 pypika-0.51.1 referencing-0.36.2 typing-inspection-0.4.2 uvicorn-0.39.0 watchfiles-1.1.1

WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.2.2 requires pyqt5<5.13, which is not installed.
spyder 5.2.2 requires pyqtwebengine<5.13, which is not installed.
mediapipe 0.10.3 requires protobuf<4,>=3.11, but you have protobuf 6.33.6 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.4 which is incompatible.
tensorflow-intel 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 6.33.6 which is incompatible.
tensorboard 2.12.2 requires google-auth-oauthlib<1.1,>=0.5, but you have google-auth-oauthlib 1.2.2 which is incompatible.
streamlit 1.50.0 requires packaging<26,>=20, but you have packaging 26.0 which is incompatible.
distributed 2022.7.0 requires dask==2022.7.0, but you have dask 2024.8.0 which is incompatible.
conda-repo-cli 1.0.20 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.20 requires nbformat==5.4.0, but you have nbformat 5.10.2 which is incompatible.
conda-repo-cli 1.0.20 requires PyYAML==6.0, but you have pyyaml 6.0.2 which is incompatible.
conda-repo-cli 1.0.20 requires requests==2.28.1, but you have requests 2.32.3 which is incompatible.
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)

In [6]:
!pip install --upgrade attrs jsonschema

Requirement already satisfied: attrs in c:\users\maithili\anaconda3\lib\site-packages (26.1.0)
Requirement already satisfied: jsonschema in c:\users\maithili\anaconda3\lib\site-packages (4.25.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\maithili\anaconda3\lib\site-packages (from jsonschema) (0.36.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\maithili\anaconda3\lib\site-packages (from jsonschema) (2025.9.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\maithili\anaconda3\lib\site-packages (from jsonschema) (0.18.1)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\maithili\anaconda3\lib\site-packages (from referencing>=0.28.4->jsonschema) (4.15.0)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)

In [2]:
!pip install openai

Collecting openai
  Using cached openai-2.30.0-py3-none-any.whl (1.1 MB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\maithili\anaconda3\lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\maithili\anaconda3\lib\site-packages (from openai) (2.10.4)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\maithili\anaconda3\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\maithili\anaconda3\lib\site-packages (from openai) (3.5.0)
Requirement already satisfied: tqdm>4 in c:\users\maithili\anaconda3\lib\site-packages (from openai) (4.66.4)
Collecting jiter<1,>=0.10.0
  Using cached jiter-0.13.0-cp39-cp39-win_amd64.whl (206 kB)
Requirement already satisfied: typing-extensions<5,>=4.14 in c:\users\maithili\anaconda3\lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: sniffio in c:\users\maithili\anaconda3\lib\site-packages (from openai) (1.2.0)
Requirement already satisfied: idna>=2.8 in c:\users\maithili\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in c:\users\maithili\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\maithili\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\maithili\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.27.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: colorama in c:\users\maithili\anaconda3\lib\site-packages (from tqdm>4->openai) (0.4.6)
Installing collected packages: jiter, openai
Successfully installed jiter-0.13.0 openai-2.30.0

WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)

In [2]:
!pip install google-generativeai

Collecting google-generativeai

WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
    WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.3 requires protobuf<4,>=3.11, but you have protobuf 4.25.9 which is incompatible.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.26.4 which is incompatible.
tensorboard 2.12.2 requires google-auth-oauthlib<1.1,>=0.5, but you have google-auth-oauthlib 1.2.2 which is incompatible.
streamlit 1.50.0 requires packaging<26,>=20, but you have packaging 26.0 which is incompatible.
opentelemetry-proto 1.40.0 requires protobuf<7.0,>=5.0, but you have protobuf 4.25.9 which is incompatible.
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\maithili\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\maithili\anaconda3\lib\site-packages)

  Downloading google_generativeai-0.8.6-py3-none-any.whl (155 kB)
     -------------------------------------- 155.1/155.1 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: google-auth>=2.15.0 in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (2.17.3)
Requirement already satisfied: tqdm in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (4.66.4)
Requirement already satisfied: typing-extensions in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: pydantic in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (2.10.4)
Requirement already satisfied: google-api-core in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (2.24.2)
Requirement already satisfied: google-api-python-client in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (2.170.0)
Requirement already satisfied: protobuf in c:\users\maithili\anaconda3\lib\site-packages (from google-generativeai) (6.33.6)
Collecting google-ai-generativelanguage==0.6.15
  Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 10.5 MB/s eta 0:00:00
Collecting protobuf
  Downloading protobuf-5.29.6-cp39-cp39-win_amd64.whl (435 kB)
     ------------------------------------- 435.2/435.2 kB 26.6 MB/s eta 0:00:00
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\maithili\anaconda3\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.23.0)
Requirement already satisfied: six>=1.9.0 in c:\users\maithili\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (1.16.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\maithili\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\maithili\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\maithili\anaconda3\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (4.9)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in c:\users\maithili\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (1.70.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in c:\users\maithili\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\maithili\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (4.1.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in c:\users\maithili\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\users\maithili\anaconda3\lib\site-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic->google-generativeai) (2.27.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\maithili\anaconda3\lib\site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: colorama in c:\users\maithili\anaconda3\lib\site-packages (from tqdm->google-generativeai) (0.4.6)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in c:\users\maithili\anaconda3\lib\site-packages (from google-api-core->google-generativeai) (1.80.0)
Collecting grpcio-status<2.0.dev0,>=1.33.2
  Downloading grpcio_status-1.80.0-py3-none-any.whl (14 kB)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\maithili\anaconda3\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.0.9)
Collecting protobuf
  Downloading protobuf-4.25.9-cp39-cp39-win_amd64.whl (413 kB)
     ------------------------------------- 413.9/413.9 kB 26.9 MB/s eta 0:00:00
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\maithili\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.4.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\maithili\anaconda3\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\maithili\anaconda3\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (1.26.20)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\maithili\anaconda3\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\maithili\anaconda3\lib\site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2024.2.2)
Collecting grpcio-status<2.0.dev0,>=1.33.2
  Downloading grpcio_status-1.78.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.76.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.75.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.73.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.73.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.71.2-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.71.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.70.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.69.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.68.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.68.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.67.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.67.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.66.2-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.66.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.66.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.65.5-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.65.4-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.65.2-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.65.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.64.3-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.64.1-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.64.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.63.2-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.63.0-py3-none-any.whl (14 kB)
  Downloading grpcio_status-1.62.3-py3-none-any.whl (14 kB)
Installing collected packages: protobuf, grpcio-status, google-ai-generativelanguage, google-generativeai
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.33.6
    Uninstalling protobuf-6.33.6:
      Successfully uninstalled protobuf-6.33.6
Successfully installed google-ai-generativelanguage-0.6.15 google-generativeai-0.8.6 grpcio-status-1.62.3 protobuf-4.25.9

In [1]:
import google.generativeai as genai

C:\Users\MAITHILI\AppData\Local\Temp\ipykernel_13800\613638648.py:1: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

In [2]:
from groq import Groq

In [3]:
import os
import pandas as pd
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
import chromadb
#from openai import OpenAI
from tqdm import tqdm

print("All imports successful!")

C:\Users\MAITHILI\anaconda3\lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
C:\Users\MAITHILI\anaconda3\lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)

All imports successful!

In [ ]:
#GROQ

GROQ_API_KEY = "*********************"       
groq_client  = Groq(api_key=GROQ_API_KEY)
MODEL        = "llama-3.1-8b-instant"


#GEMINI 
import google.generativeai as genai

genai.configure(api_key="******************")

vision_model = genai.GenerativeModel(
    model_name="models/gemini-2.5-flash"
)

print("Groq   ready — classifier, responder, evaluator, guardrails")
print("Gemini ready — vision agent only")

Groq   ready — classifier, responder, evaluator, guardrails
Gemini ready — vision agent only

In [5]:
print("Loading dataset from hugging face transformers")

#ds = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset")
df = pd.read_csv("../data/raw/support_dataset.csv")
#df = ds["train"].to_pandas()

print(f"Shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nCategories:\n{df['category'].value_counts()}")

Loading dataset from hugging face transformers
Shape: (26872, 5)

Columns: ['flags', 'instruction', 'category', 'intent', 'response']

Categories:
category
ACCOUNT         5986
ORDER           3988
REFUND          2992
INVOICE         1999
CONTACT         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

In [6]:
df.head()

,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...

In [7]:
df['category'].value_counts()

category
ACCOUNT         5986
ORDER           3988
REFUND          2992
INVOICE         1999
CONTACT         1999
PAYMENT         1998
FEEDBACK        1997
DELIVERY        1994
SHIPPING        1970
SUBSCRIPTION     999
CANCEL           950
Name: count, dtype: int64

In [8]:
df.isnull().sum() #no missing values

flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64

In [9]:
df[["instruction", "response", "category", "intent"]].head(5)

,instruction,response,category,intent
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...,ORDER,cancel_order
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...,ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...,ORDER,cancel_order
3,I need to cancel purchase {{Order Number}},I understood that you need assistance with can...,ORDER,cancel_order
4,"I cannot afford this order, cancel purchase {{...",I'm sensitive to the fact that you're facing f...,ORDER,cancel_order

In [10]:
os.makedirs("../data/raw", exist_ok=True)
df.to_csv("../data/raw/support_dataset.csv", index=False)
print(f"Saved {len(df)} rows to data/raw/support_dataset.csv")

Saved 26872 rows to data/raw/support_dataset.csv

In [ ]:
# Cleaning the dataset - since most of our dataset is already clean only few necessary changes

# Dropping duplicates, stripping whitespace, keeping only what we need
df_clean = df[["instruction", "response", "category", "intent"]].copy()
df_clean = df_clean.drop_duplicates(subset=["response"])
df_clean = df_clean.dropna()
df_clean["instruction"] = df_clean["instruction"].str.strip()
df_clean["response"]    = df_clean["response"].str.strip()

os.makedirs("../data/processed", exist_ok=True)
df_clean.to_csv("../data/processed/support_clean.csv", index=False)

print(f"Cleaned shape: {df_clean.shape}")
df_clean.head(3)

Cleaned shape: (26870, 4)

,instruction,response,category,intent
0,question about cancelling order {{Order Number}},I've understood you have a question regarding ...,ORDER,cancel_order
1,i have a question about cancelling oorder {{Or...,I've been informed that you have a question ab...,ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},I can sense that you're seeking assistance wit...,ORDER,cancel_order

In [12]:
# Building the knowledge base

# The knowledge base means the "responses" column, these are the good answers the system will retrieve from

os.makedirs("../data/knowledge_base", exist_ok=True)

kb_docs = []
for _, row in df_clean.iterrows():
    kb_docs.append({
        "text":     row["response"],
        "category": row["category"],
        "intent":   row["intent"]
    })

print(f"Knowledge base size: {len(kb_docs)} documents")
print(f"\nExample document:")
print(kb_docs[0])

Knowledge base size: 26870 documents

Example document:
{'text': "I've understood you have a question regarding canceling order {{Order Number}}, and I'm here to provide you with the information you need. Please go ahead and ask your question, and I'll do my best to assist you.", 'category': 'ORDER', 'intent': 'cancel_order'}

In [13]:
#Creating embedding and storing in ChromaDB

print("Loading embedding model (downloads once ~80MB)...")
embedder = SentenceTransformer("all-MiniLM-L6-v2")
print("Embedding model ready!")

chroma_client = chromadb.PersistentClient(path="../vector_store")
collection = chroma_client.get_or_create_collection(
    name="support_kb",
    metadata={"hnsw:space": "cosine"}
)

print(f"Collection ready. Current doc count: {collection.count()}")

Loading embedding model (downloads once ~80MB)...
Embedding model ready!
Collection ready. Current doc count: 26870

In [14]:
# Only embed if collection is empty (avoids re-embedding on restart)
if collection.count() == 0:
    print("Embedding and storing documents...")
    batch_size = 100

    for i in tqdm(range(0, len(kb_docs), batch_size)):
        batch     = kb_docs[i : i + batch_size]
        texts     = [doc["text"] for doc in batch]
        embeddings = embedder.encode(texts, show_progress_bar=False).tolist()

        collection.add(
            documents  = texts,
            embeddings = embeddings,
            metadatas  = [{"category": d["category"], "intent": d["intent"]} for d in batch],
            ids        = [f"doc_{i+j}" for j in range(len(batch))]
        )

    print(f"Done! Stored {collection.count()} documents.")
else:
    print(f"Collection already has {collection.count()} docs. Skipping embedding.")

Collection already has 26870 docs. Skipping embedding.

In [15]:
def retrieve_docs(query: str, top_k: int = 3):
    q_embedding = embedder.encode([query]).tolist()
    results = collection.query(
        query_embeddings=q_embedding,
        n_results=top_k
    )
    return results["documents"][0], results["metadatas"][0]


def generate_answer(query: str, context_docs: list) -> str:
    context = "\n\n".join([f"Doc {i+1}: {doc}" for i, doc in enumerate(context_docs)])

    prompt = f"""You are a helpful customer support agent.
Use the knowledge base excerpts below to answer the customer's question.
If the answer isn't in the excerpts, say so honestly — do not make things up.

Knowledge Base:
{context}

Customer Question: {query}

Answer:"""

    response = groq_client.chat.completions.create(
        model       = MODEL,
        messages    = [{"role": "user", "content": prompt}],
        temperature = 0.3
    )
    return response.choices[0].message.content.strip()


def rag_pipeline(query: str):
    print(f"Query: {query}\n")
    docs, metas = retrieve_docs(query)
    answer = generate_answer(query, docs)

    print(f"Answer:\n{answer}")
    print(f"\nSources used:")
    for i, m in enumerate(metas):
        print(f"  [{i+1}] category={m['category']}  intent={m['intent']}")
    return answer

In [16]:
rag_pipeline("I can't reset my password")

Query: I can't reset my password

Answer:
I'd be happy to help you reset your password. Based on our knowledge base, here are the steps you can follow:

1. Visit the login page of our platform.
2. Look for the option that says "Forgot Password" and click on it.
3. You will be prompted to enter your email address associated with your account.
4. After entering your email, you should receive an email with instructions on how to reset your password. Please check your inbox, and if you don't see it, be sure to check your spam or junk folder.
5. Follow the instructions provided in the email to reset your password. Make sure to create a strong password that includes a combination of letters, numbers, and symbols.

If you've already tried these steps and are still having trouble, please let me know and I'll be happy to assist you further.

Sources used:
  [1] category=ACCOUNT  intent=recover_password
  [2] category=ACCOUNT  intent=recover_password
  [3] category=ACCOUNT  intent=recover_password

'I\'d be happy to help you reset your password. Based on our knowledge base, here are the steps you can follow:\n\n1. Visit the login page of our platform.\n2. Look for the option that says "Forgot Password" and click on it.\n3. You will be prompted to enter your email address associated with your account.\n4. After entering your email, you should receive an email with instructions on how to reset your password. Please check your inbox, and if you don\'t see it, be sure to check your spam or junk folder.\n5. Follow the instructions provided in the email to reset your password. Make sure to create a strong password that includes a combination of letters, numbers, and symbols.\n\nIf you\'ve already tried these steps and are still having trouble, please let me know and I\'ll be happy to assist you further.'

In [17]:
rag_pipeline("I was charged twice for my order")

Query: I was charged twice for my order

Answer:
Based on the knowledge base excerpts provided, I can assist you with your concern.

According to Doc 1, Doc 2, and Doc 3, if you notice duplicate charges for the same product or service, you can request a reimbursement. This is listed under point 5 in each of the documents:

- Doc 1: "5. **Duplicate Charges:** If you notice duplicate charges for the same product or service, please reach out to us, and we will assist you in resolving the issue and obtaining a reimbursement if applicable."
- Doc 2: "5. **Duplicate Charges:** Accidental double charges can occur. If you notice that you have been charged more than once for the same item, please reach out to us so that we can rectify the situation promptly."
- Doc 3: "5. **Duplicate Charges:** If you notice multiple charges for the same item on your statement, please contact us as soon as possible. We will promptly rectify the situation and ensure you receive a reimbursement for the duplicate charges."

To initiate the reimbursement process, please provide me with your order number and any other relevant details, and I will be happy to assist you further.

Sources used:
  [1] category=REFUND  intent=check_refund_policy
  [2] category=REFUND  intent=check_refund_policy
  [3] category=REFUND  intent=check_refund_policy

'Based on the knowledge base excerpts provided, I can assist you with your concern. \n\nAccording to Doc 1, Doc 2, and Doc 3, if you notice duplicate charges for the same product or service, you can request a reimbursement. This is listed under point 5 in each of the documents:\n\n- Doc 1: "5. **Duplicate Charges:** If you notice duplicate charges for the same product or service, please reach out to us, and we will assist you in resolving the issue and obtaining a reimbursement if applicable."\n- Doc 2: "5. **Duplicate Charges:** Accidental double charges can occur. If you notice that you have been charged more than once for the same item, please reach out to us so that we can rectify the situation promptly."\n- Doc 3: "5. **Duplicate Charges:** If you notice multiple charges for the same item on your statement, please contact us as soon as possible. We will promptly rectify the situation and ensure you receive a reimbursement for the duplicate charges."\n\nTo initiate the reimbursement process, please provide me with your order number and any other relevant details, and I will be happy to assist you further.'

In [18]:
import os

vs_path = "../vector_store"
files = os.listdir(vs_path)
print(f"Vector store files: {files}")
print(f"Total KB docs in collection: {collection.count()}")

Vector store files: ['3663896d-dbba-4e55-95e0-aa41133bbfea', 'chroma.sqlite3']
Total KB docs in collection: 26870

In [19]:
rag_pipeline("How do I cancel my subscription?")

Query: How do I cancel my subscription?

Answer:
To cancel your subscription, you can visit our website and go to the account settings page. From there, you should be able to find an option to cancel your subscription. If you encounter any difficulties or have any further questions, please don't hesitate to let me know.

Sources used:
  [1] category=ACCOUNT  intent=delete_account
  [2] category=ACCOUNT  intent=delete_account
  [3] category=ACCOUNT  intent=delete_account

"To cancel your subscription, you can visit our website and go to the account settings page. From there, you should be able to find an option to cancel your subscription. If you encounter any difficulties or have any further questions, please don't hesitate to let me know."

Data layer — you downloaded a real dataset of 26,000+ customer support conversations from HuggingFace, cleaned it (removed duplicates, nulls, whitespace), and saved both raw and processed versions to disk.

Knowledge base — you took the response column from the dataset and turned it into a searchable knowledge base. These are the "good answers" your system learns from.

Embeddings — you used all-MiniLM-L6-v2 (a free, local model) to convert every KB document into a vector — a list of numbers that captures the meaning of the text. Similar questions get similar vectors.

Vector store — you stored all those vectors in ChromaDB, persisted to disk. This means when someone asks a question, you can instantly find the most semantically similar KB documents without scanning all 26,000 rows one by one.

RAG pipeline — you connected everything into one function: question comes in → gets embedded → top 3 similar docs retrieved → docs + question sent to LLM → grounded answer comes out. The LLM never guesses — it answers based on real retrieved knowledge.